name: バグ報告
description: 期待と異なる挙動の報告
title: "[BUG] <簡単な概要>"
labels: ["bug"]
body:
    - type: textarea
      id: behavior
      attributes:
          label: 現状の挙動
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: 期待する挙動
      validations:
          required: true
    - type: textarea
      id: reproduce
      attributes:
          label: 再現手順
      validations:
          required: false
    - type: textarea
      id: environment
      attributes:
          label: 環境情報
          description: OS、言語/ランタイムのバージョンなど
      validations:
          required: false
